name: Build and deploy Node.js app to Azure Web App - m3turnersapicv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

      - name: Set Name Variables
        id: set-variables
        run: |
          echo "version=$(git describe --tags --always)" >> $GITHUB_ENV
          echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        shell: bash

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-report-${{ steps.set-variables.outputs.version }}-${{ steps.set-variables.outputs.timestamp }}
          path: coverage/${{ steps.set-variables.outputs.timestamp }}/*
